version: 2

sources:
  - name: erp
    description: Fonte SAP de vendas da Northwind
    schema: erp_northwind
    tables:
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null
      - name: categories
      - name: suppliers
      - name: employees
      - name: orders
        description: Tabela de pedidos onde só podemos ter uma nota fiscal por linha, sendo não nula.
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details
